services:
  web:
    build: .
    container_name: cybervisionx-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_DEBUG: "true"
      ENABLE_CELERY: "true"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    container_name: cybervisionx-worker
    command: celery -A config worker --loglevel=INFO
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      ENABLE_CELERY: "true"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: cybervisionx-redis
    ports:
      - "6379:6379"
